baseURL = 'https://aimloul.com/'
languageCode = 'en-us'
title = 'aimloul'
theme = 'aimloul'
[pagination]
  pagerSize = 5

[params]
  author = 'Imloul Anas'
  description = 'Writing about database internals, systems design, and backend engineering.'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    noClasses = true
    style = 'nord'
    lineNos = false
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block  = [["$$", "$$"]]
        inline = [["$", "$"]]
